project:
  type: book
  output-dir: _book

book:
  title: "R for Data Science (2e)"

  author-meta: "Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund"
  date-meta: today
  description-meta: |
    This book will teach you how to do data science with R: You'll learn how to
    get your data into R, get it into the most useful structure, transform it,
    visualise it, and model it. In this book, you will find a practicum of
    skills for data science. Just as a chemist learns how to clean test tubes
    and stock a lab, you'll learn how to clean data and draw plots---and many
    other things besides. These are the skills that allow data science to
    happen, and here you will find the best practices for doing each of these
    things with R. You'll learn how to use the grammar of graphics, literate
    programming to save time and make your work reproducible. Along the way,
    you'll also learn how to manage cognitive resources to facilitate
    discoveries when wrangling, visualising, and exploring data.

  reader-mode: true

  page-footer:
    left: |
      R for Data Science (2e) was written by Hadley Wickham, Mine
      Çetinkaya-Rundel, and Garrett Grolemund.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/hadley/r4ds/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - preface-2e.qmd
    - intro.qmd

    - part: whole-game.qmd
      chapters:
        - data-visualize.qmd
        - workflow-basics.qmd
        - data-transform.qmd
        - workflow-pipes.qmd
        - data-tidy.qmd
        - workflow-style.qmd
        - data-import.qmd
        - workflow-scripts.qmd
        - EDA.qmd
        - workflow-help.qmd

    - part: transform.qmd
      chapters:
        - logicals.qmd
        - numbers.qmd
        - strings.qmd
        - regexps.qmd
        - factors.qmd
        - datetimes.qmd
        - missing-values.qmd
        - joins.qmd

    - part: wrangle.qmd
      chapters:
        - parsing.qmd
        - spreadsheets.qmd
        - databases.qmd
        - rectangling.qmd
        - webscraping.qmd

    - part: program.qmd
      chapters:
        - functions.qmd
        - vectors.qmd
        - tibble.qmd
        - iteration.qmd

    - part: communicate.qmd
      chapters:
        - quarto.qmd
        - communicate-plots.qmd
        - quarto-formats.qmd
        - quarto-workflow.qmd

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    cover-image: cover.png
    code-link: true
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

